### ISSUE TITLE
Crash when updating from 6.0.18 to 6.1.8

### ISSUE THREAD

**Issue by JeffreyTehGamer** [BuildCraft/BuildCraft#2206]
I updated my buildcraft and it crashed when loading minecraft I deleted the old folder/config when i updated as well 
[spoiler] ---- Minecraft Crash Report ----
// Don't do that.

Time: 11/11/14 11:17 PM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoSuchMethodError: buildcraft.api.recipes.IRefineryRecipeManager.addRecipe(Ljava/lang/String;Lnet/minecraftforge/fluids/FluidStack;Lnet/minecraftforge/fluids/FluidStack;II)V
    at cpw.mods.fml.common.LoadController.transition(LoadController.java:162)
    at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:515)
    at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:239)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:286)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:376)
    at org.multimc.EntryPoint.listen(EntryPoint.java:165)
    at org.multimc.EntryPoint.main(EntryPoint.java:54)
Caused by: java.lang.NoSuchMethodError: buildcraft.api.recipes.IRefineryRecipeManager.addRecipe(Ljava/lang/String;Lnet/minecraftforge/fluids/FluidStack;Lnet/minecraftforge/fluids/FluidStack;II)V
    at buildcraft.BuildCraftEnergy.preInit(BuildCraftEnergy.java:250)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
    at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
    at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:513)
    ... 18 more
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Mac OS X (x86_64) version 10.10
    Java Version: 1.7.0_60, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 500352944 bytes (477 MB) / 2041053184 bytes (1946 MB) up to 3817865216 bytes (3641 MB)
    JVM Flags: 3 total; -Xms512m -Xmx4096m -XX:PermSize=1048m
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.85.1235 Minecraft Forge 10.13.2.1235 Optifine OptiFine_1.7.10_HD_U_A4 182 mods loaded, 182 mods active
    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized
    FML{7.10.85.1235} [Forge Mod Loader](forge-1.7.10-10.13.2.1235-universal.jar) Unloaded->Constructed->Pre-initialized
    Forge{10.13.2.1235} [Minecraft Forge](forge-1.7.10-10.13.2.1235-universal.jar) Unloaded->Constructed->Pre-initialized
    AppleMilkCore{1.0.2} [AppleMilkCore](minecraft.jar) Unloaded->Constructed->Pre-initialized
    AppliedEnergistics2-Core{rv0-stable-10} [AppliedEnergistics2 Core](minecraft.jar) Unloaded->Constructed->Pre-initialized
    Aroma1997Core{1.0.2.11} [Aroma1997Core](Aroma1997Core-1.7.10-1.0.2.11.jar) Unloaded->Constructed->Pre-initialized
    CodeChickenCore{1.0.2.9} [CodeChicken Core](minecraft.jar) Unloaded->Constructed->Pre-initialized
    <CoFH ASM>{000} [CoFH ASM Data Initialization](minecraft.jar) Unloaded->Constructed->Pre-initialized
    <DragonAPI ASM>{0} [DragonAPI ASM Data Initialization](minecraft.jar) Unloaded->Constructed->Pre-initialized
    NotEnoughItems{1.0.2.15} [Not Enough Items](NotEnoughItems-1.7.10-1.0.2.15-universal.jar) Unloaded->Constructed->Pre-initialized
    OpenEye{0.6} [OpenEye](OpenEye-0.6-1.7.10.jar) Unloaded->Constructed->Pre-initialized
    PlayerAPI{1.1} [Player API](minecraft.jar) Unloaded->Constructed->Pre-initialized
    PotionExtensionCore{1.0.1} [PotionExtensionCore](minecraft.jar) Unloaded->Constructed->Pre-initialized
    OpenModsCore{@VERSION@} [OpenModsCore](minecraft.jar) Unloaded->Constructed->Pre-initialized
    FamiliarsAPI{1.7.10} [Familiars API](FamiliarsAPI-1.7.10.jar) Unloaded->Constructed->Pre-initialized
    Baubles{1.0.1.8} [Baubles](Baubles-1.7.10-1.0.1.8.jar) Unloaded->Constructed->Pre-initialized
    Thaumcraft{4.2.0.1} [Thaumcraft](Thaumcraft-1.7.10-4.2.0.1.jar) Unloaded->Constructed->Pre-initialized
    arsmagica2{1.4.0.005} [Ars Magica 2](1.7.10_AM2_1.4.0.005.jar) Unloaded->Constructed->Pre-initialized
    lucky{5.1.0} [Lucky Block]([1-7-10]_Lucky_Block_v5-1-0.jar) Unloaded->Constructed->Pre-initialized
    infcraft{2.45} [�5InfusionCraft]([1.7.10] InfusionCraft v 2.45.jar) Unloaded->Constructed->Pre-initialized
    simpleores{1.4.3} [SimpleOres 2]([1.7.10] SimpleOres 2   Plugins v1.4.3 .jar) Unloaded->Constructed->Pre-initialized
    aestheticsplugin{1.0.0} [SimpleOres 2 Aesthetics Plugin]([1.7.10] SimpleOres 2   Plugins v1.4.3 .jar) Unloaded->Constructed->Pre-initialized
    fusionplugin{1.4.3} [SimpleOres 2 Fusion Plugin]([1.7.10] SimpleOres 2   Plugins v1.4.3 .jar) Unloaded->Constructed->Pre-initialized
    netherrocks{1.1.2} [SimpleOres 2 Netherrocks Plugin]([1.7.10] SimpleOres 2   Plugins v1.4.3 .jar) Unloaded->Constructed->Pre-initialized
    SC0_SpaceCore{0.7.12} [SpaceCore]([1.7.10] SpaceCore 0.7.12.jar) Unloaded->Constructed->Pre-initialized
    SC0_Wings{1.2.6} [Survival Wings]([1.7.10] Survival Wings 1.2.6.jar) Unloaded->Constructed->Pre-initialized
    FLabsBF{4.1.2} [Better Furnaces]([1.7.10]Better_Furnaces_V4.1.2.jar) Unloaded->Constructed->Pre-initialized
    DamageIndicatorsMod{3.2.0} [Damage Indicators]([1.7.10]DamageIndicatorsMod-3.2.0.jar) Unloaded->Constructed->Pre-initialized
    IMSM{100.0.2} [IMSM]([1.7.10]InstantMassiveStructuresMod.jar) Unloaded->Constructed->Pre-initialized
    woodconverter{v2.7_1} [Wood Converter]([1.7.10]Wood Converter v2.7_1.jar) Unloaded->Constructed->Pre-initialized
    bspkrsCore{6.14} [bspkrsCore]([1.7.10]bspkrsCore-universal-6.14.jar) Unloaded->Constructed->Pre-initialized
    Treecapitator{1.7.2} [Treecapitator]([1.7.2]Treecapitator-universal-2.0.3.jar) Unloaded->Constructed->Pre-initialized
    deconstruction{2.2.5} [The Deconstruction Mod]([MC1.7.10]deconstruction[v2.2.5].jar) Unloaded->Constructed->Pre-initialized
    DCsAppleMilk{1.7.10_2.0.alpha13} [Apple&Milk&Tea!](AppleMilkTea2-1.7.10_2.0_alpha13.jar) Unloaded->Constructed->Pre-initialized
    CoFHCore{1.7.10R3.0.0B8} [CoFH Core](CoFHCore-[1.7.10]3.0.0B8-36.jar) Unloaded->Constructed->Pre-initialized
    BuildCraft|Core{6.1.8} [BuildCraft](buildcraft-6.1.8.jar) Unloaded->Constructed->Pre-initialized
    ThermalFoundation{1.7.10R1.0.0B3} [Thermal Foundation](ThermalFoundation-[1.7.10]1.0.0B3-8.jar) Unloaded->Constructed->Pre-initialized
    ThermalExpansion{1.7.10R4.0.0B5} [Thermal Expansion](ThermalExpansion-[1.7.10]4.0.0B5-13.jar) Unloaded->Constructed->Pre-initialized
    appliedenergistics2{rv0-stable-10} [Applied Energistics 2](appliedenergistics2-rv0-stable-10.jar) Unloaded->Constructed->Pre-initialized
    Aquaculture{1.2.3} [Aquaculture](Aquaculture-1.7.10-1.2.5.8.jar) Unloaded->Constructed->Pre-initialized
    Aroma1997CoreHelper{1.0.2.11} [Aroma1997Core|Helper](Aroma1997Core-1.7.10-1.0.2.11.jar) Unloaded->Constructed->Pre-initialized
    AromaBackup{0.0.0.5} [AromaBackup](AromaBackup-1.7.10-0.0.0.5.jar) Unloaded->Constructed->Pre-initialized
    Artifacts{1.0.6} [Artifacts](Artifacts-1.0.6.jar) Unloaded->Constructed->Pre-initialized
    Backpack{2.0.1} [Backpack](backpack-2.0.1-1.7.x.jar) Unloaded->Constructed->Pre-initialized
    iChunUtil{4.0.0} [iChunUtil](iChunUtil-4.0.0.jar) Unloaded->Constructed->Pre-initialized
    BackTools{4.0.0} [BackTools](BackTools-4.0.0.jar) Unloaded->Constructed->Pre-initialized
    BetterChests{1.1.1.7} [BetterChests](BetterChests-1.7.10-1.1.1.7.jar) Unloaded->Constructed->Pre-initialized
    bettersprinting{1.0} [Better Sprinting](BetterSprinting.jar) Unloaded->Constructed->Pre-initialized
    bettervillages{0.3} [Better Villages Mod](BetterVillages-0.3%281.7.10%29.jar) Unloaded->Constructed->Pre-initialized
    BiblioCraft{1.9.0} [BiblioCraft](BiblioCraft[v1.9.0][MC1.7.10].jar) Unloaded->Constructed->Pre-initialized
    ExtrabiomesXL{3.16.0} [ExtrabiomesXL](extrabiomesxl_1.7.10-3.16.0.jar) Unloaded->Constructed->Pre-initialized
    BiblioWoodsEBXL{1.4} [BiblioWoods ExtraBiomesXL Edition](BiblioWoods[ExtraBiomesXL][v1.4].jar) Unloaded->Constructed->Pre-initialized
    Mantle{1.7.10-0.3.2.jenkins184} [Mantle](Mantle-1.7.10-0.3.2.jar) Unloaded->Constructed->Pre-initialized
    Natura{2.2.0} [Natura](natura-1.7.10-2.2.0.1.jar) Unloaded->Constructed->Pre-initialized
    BiblioWoodsNatura{1.5} [BiblioWoods Natura Edition](BiblioWoods[Natura][v1.5].jar) Unloaded->Constructed->Pre-initialized
    Botania{r1.3-134} [Botania](Botania r1.3-134.jar) Unloaded->Constructed->Pre-initialized
    BuildCraft|Builders{6.1.8} [BC Builders](buildcraft-6.1.8.jar) Unloaded->Constructed->Pre-initialized
    BuildCraft|Energy{6.1.8} [BC Energy](buildcraft-6.1.8.jar) Unloaded->Constructed->Errored
    BuildCraft|Factory{6.1.8} [BC Factory](buildcraft-6.1.8.jar) Unloaded->Constructed->Pre-initialized
    BuildCraft|Transport{6.1.8} [BC Transport](buildcraft-6.1.8.jar) Unloaded->Constructed->Pre-initialized
    BuildCraft|Silicon{6.1.8} [BC Silicon](buildcraft-6.1.8.jar) Unloaded->Constructed->Pre-initialized
    butterflymania{1.1.2} [Butterfly Mania](butterflymania-1.7.10-1.1.2.jar) Unloaded->Constructed->Pre-initialized
    BWG4{1.2.1} [Better World Generation 4](BWG4-1.2.1.jar) Unloaded->Constructed->Pre-initialized
    candycraftmod{Beta 1.3} [CandyCraft](CandyCraft-1.3.jar) Unloaded->Constructed->Pre-initialized
    CarpentersBlocks{3.3.1} [Carpenter's Blocks](Carpenter's Blocks v3.3.1 - MC 1.7.10.jar) Unloaded->Constructed->Pre-initialized
    chisel{1.5.7} [Chisel](Chisel-1.7.10-1.5.7.jar) Unloaded->Constructed->Pre-initialized
    Mystcraft{0.11.0.00} [Mystcraft](mystcraft-1.7.10-0.11.0.00.jar) Unloaded->Constructed->Pre-initialized
    ForgeMultipart{1.1.0.300} [Forge Multipart](ForgeMultipart-1.7.10-1.1.0.300-universal.jar) Unloaded->Constructed->Pre-initialized
    ProjRed|Core{4.4.9.49} [ProjectRed](ProjectRed-Base-1.7.10-4.4.9.49.jar) Unloaded->Constructed->Pre-initialized
    Waila{1.5.5} [Waila](Waila-1.5.5_1.7.10.jar) Unloaded->Constructed->Pre-initialized
    DragonAPI{1.0} [DragonAPI](DragonAPI 1.7.10 V2.jar) Unloaded->Constructed->Pre-initialized
    ChromatiCraft{Alpha} [ChromatiCraft](ChromatiCraft 1.7.10 V2.jar) Unloaded->Constructed->Pre-initialized
    teamod{1.2.1} [Richard's Coffee & Tea Mod](CoffeeAndTeaMod-1.2.1.jar) Unloaded->Constructed->Pre-initialized
    colourfulportalsmod{1.4.2} [Colourful Portals](ColourfulPortals-1.4.2_for_1.7.X.jar) Unloaded->Constructed->Pre-initialized
    craftingpillars{1.5.5} [Crafting Pillars](craftingpillars-1.7.10-1.5.8.jar) Unloaded->Constructed->Pre-initialized
    props{1.11} [Decocraft](Decocraft-v1.11_1.7.10.jar) Unloaded->Constructed->Pre-initialized
    DynamicLights{1.3.7} [Dynamic Lights](DynamicLights-1.7.10.jar) Unloaded->Constructed->Pre-initialized
    DynamicLights_onFire{1.0.4} [Dynamic Lights Burning Entity Module](DynamicLights-1.7.10.jar) Unloaded->Constructed->Pre-initialized
    DynamicLights_creepers{1.0.4} [Dynamic Lights Creeper Module](DynamicLights-1.7.10.jar) Unloaded->Constructed->Pre-initialized
    DynamicLights_dropItems{1.0.7} [Dynamic Lights EntityItem Module](DynamicLights-1.7.10.jar) Unloaded->Constructed->Pre-initialized
    DynamicLights_entityClasses{1.0.1} [Dynamic Lights Entity Light Module](DynamicLights-1.7.10.jar) Unloaded->Constructed->Pre-initialized
    DynamicLights_mobEquipment{1.0.7} [Dynamic Lights Mob Equipment Light Module](DynamicLights-1.7.10.jar) Unloaded->Constructed->Pre-initialized
    DynamicLights_flameArrows{1.0.0} [Dynamic Lights Fiery Arrows Light Module](DynamicLights-1.7.10.jar) Unloaded->Constructed->Pre-initialized
    DynamicLights_floodLights{1.0.1} [Dynamic Lights Flood Light](DynamicLights-1.7.10.jar) Unloaded->Constructed->Pre-initialized
    DynamicLights_otherPlayers{1.0.7} [Dynamic Lights OtherPlayers Light Module](DynamicLights-1.7.10.jar) Unloaded->Constructed->Pre-initialized
    DynamicLights_thePlayer{1.1.3} [Dynamic Lights Player Light Module](DynamicLights-1.7.10.jar) Unloaded->Constructed->Pre-initialized
    LunatriusCore{1.1.2.14} [LunatriusCore](LunatriusCore-1.7.10-1.1.2.14-universal.jar) Unloaded->Constructed->Pre-initialized
    DynIMC{1.1.0.5} [DynIMC](DynIMC-1.7.10-1.1.0.5-universal.jar) Unloaded->Constructed->Pre-initialized
    Emotes{1.0} [Emotes](Emotes 1.0.jar) Unloaded->Constructed->Pre-initialized
    eplus{3.0.2-d} [Enchanting Plus](EnchantingPlus-1.7.10-3.0.2-d.jar) Unloaded->Constructed->Pre-initialized
    thebombzenapi{2.4.1} [ThebombzenAPI](ThebombzenAPI-v2.4.1-mc1.7.2.jar) Unloaded->Constructed->Pre-initialized
    enchantview{4.0.4} [EnchantView](EnchantView-v4.0.4-mc1.7.10.jar) Unloaded->Constructed->Pre-initialized
    ether{3.0} [ether](ether-1.7.10-0.7.13.jar) Unloaded->Constructed->Pre-initialized
    DefaultMobPack{1.7.10} [DefaultMobPack](FamiliarsDefaultMobPack-1.7.10.jar) Unloaded->Constructed->Pre-initialized
    ExtendedFamPack{1.7.10} [ExtendedFamPack](FamiliarsExtendedFamPack-1.7.10.jar) Unloaded->Constructed->Pre-initialized
    HerobrineFamPack{1.7.10} [HerobrineFamPack](FamiliarsHerobrineFamPack-1.7.10.jar) Unloaded->Constructed->Pre-initialized
    flowercraftmod{1.9} [Flowercraft](Flowercraftmod 1.8 - 1.7.10 Forge.jar) Unloaded->Constructed->Pre-initialized
    fossil{1.7.10 Build 6.4b} [Fossils and Archeology Revival](Fossils_Archeology_Revival-1.7.10_Build-6.4b.jar) Unloaded->Constructed->Pre-initialized
    foxlib{1.7.10-0.6.0} [FoxLib](FoxLib-1.7.10-0.6.0.jar) Unloaded->Constructed->Pre-initialized
    freerun{0.1} [Free Runner Mod](FreeRunner-0.1%281.7.10%29.jar) Unloaded->Constructed->Pre-initialized
    GeoStrata{Gamma} [GeoStrata](GeoStrata 1.7.10 V2.jar) Unloaded->Constructed->Pre-initialized
    Growthcraft{2.1.0a} [Growthcraft](growthcraft-core-1.7.10-2.1.0a.jar) Unloaded->Constructed->Pre-initialized
    Growthcraft|Cellar{2.1.0a} [Growthcraft Cellar](growthcraft-cellar-1.7.10-2.1.0a.jar) Unloaded->Constructed->Pre-initialized
    Growthcraft|Apples{2.1.0} [Growthcraft Apples](growthcraft-apples-1.7.10-2.1.0.jar) Unloaded->Constructed->Pre-initialized
    Growthcraft|Bamboo{2.1.0} [Growthcraft Bamboo](growthcraft-bamboo-1.7.10-2.1.0.jar) Unloaded->Constructed->Pre-initialized
    Growthcraft|Bees{2.1.0} [Growthcraft Bees](growthcraft-bees-1.7.10-2.1.0.jar) Unloaded->Constructed->Pre-initialized
    Growthcraft|Fishtrap{2.1.0a} [Growthcraft Fishtrap](growthcraft-fishtrap-1.7.10-2.1.0a.jar) Unloaded->Constructed->Pre-initialized
    Growthcraft|Grapes{2.1.0} [Growthcraft Grapes](growthcraft-grapes-1.7.10-2.1.0.jar) Unloaded->Constructed->Pre-initialized
    Growthcraft|Hops{2.1.0} [Growthcraft Hops](growthcraft-hops-1.7.10-2.1.0.jar) Unloaded->Constructed->Pre-initialized
    Growthcraft|Rice{2.1.0a} [Growthcraft Rice](growthcraft-rice-1.7.10-2.1.0a.jar) Unloaded->Constructed->Pre-initialized
    hamsterrific{0.2.0} [Hamsterrific](Hamsterrific-0.2.0.jar.zip) Unloaded->Constructed->Pre-initialized
    haycraftmod{1.7} [Haycraft](Haycraftmod 1.7 - 1.7.10 Forge.jar) Unloaded->Constructed->Pre-initialized
    HopperDuctMod{1.3.2} [Hopper Ducts](hopperductmod-1.7.10-1.3.2.jar) Unloaded->Constructed->Pre-initialized
    hybridcraft{v1.2} [HybridCraft: Refused](HybridCraft-Refused v1.2 for 1.7.2.jar) Unloaded->Constructed->Pre-initialized
    fyrestorm_icecreamcreepermod{1.0.9d} [Icecream Sandwich Creeper Mod](IceCreamSandwichCreeperModv1.0.9e.jar) Unloaded->Constructed->Pre-initialized
    instahouse{6.3} [Insta House](Insta House v 6.3.jar) Unloaded->Constructed->Pre-initialized
    instantblocks{1.5.2} [Instant Blocks](InstantBlocks_v1.5.2.jar) Unloaded->Constructed->Pre-initialized
    inventorytweaks{1.58-147-645ca10} [Inventory Tweaks](InventoryTweaks-1.58-147.jar) Unloaded->Constructed->Pre-initialized
    IronChest{6.0.62.742} [Iron Chest](ironchest-1.7.10-6.0.62.742-universal.jar) Unloaded->Constructed->Pre-initialized
    wuppy29_koi{1.11.2} [Koi](Koi 1.7.10-1.11.2.jar) Unloaded->Constructed->Pre-initialized
    LightBridgesAndDoors{0.2.0} [kris91268's Light Bridges and Doors](Light Bridges and Doors V 2.0.zip) Unloaded->Constructed->Pre-initialized
    LomLib{3.0.0} [LomLib](LomLib-1.7.10-3.0.0-universal.jar) Unloaded->Constructed->Pre-initialized
    magicalcrops{1.7.2 - 0.1 ALPHA} [Magical Crops](magicalcrops-1.7.10_0.1.jar) Unloaded->Constructed->Pre-initialized
    MapWriter{2.1710.1} [MapWriter](MapWriter-1.7.10-2.1710.2.jar) Unloaded->Constructed->Pre-initialized
    radixcore{1.3.4} [RadixCore](RadixCore-1.7.10-1.3.4-universal.jar) Unloaded->Constructed->Pre-initialized
    mca{4.1.5} [Minecraft Comes Alive](MCA-1.7.10-4.1.5-universal.jar) Unloaded->Constructed->Pre-initialized
    MetallurgyCore{4.0.4} [Metallurgy Core](MetallurgyCore-1.7.10-4.0.4.18.jar) Unloaded->Constructed->Pre-initialized
    Metallurgy{4.0.6} [Metallurgy 4](Metallurgy-1.7.10-4.0.6.80.jar) Unloaded->Constructed->Pre-initialized
    meteors{2.13.1} [Falling Meteors](meteors-1.7.10-2.13.1.jar) Unloaded->Constructed->Pre-initialized
    mfm{v2.1.0} [Mo' Furnaces Mod](mfm-1.7.10-2.1.0.jar) Unloaded->Constructed->Pre-initialized
    Mo' Shiz{1.51} [Mo' Shiz](Mo' Shiz v1.52.jar) Unloaded->Constructed->Pre-initialized
    ModularForcefieldSystem{3.0-ALPHA-7} [Modular Forcefield System](ModularForcefieldSystem-1.7.10-3.0-ALPHA-7.jar) Unloaded->Constructed->Pre-initialized
    cfm{3.3.6} [�6MrCrayfish's Furniture Mod](MrCrayfishFurnitureModv3.3.6%281.7.10%29.jar) Unloaded->Constructed->Pre-initialized
    MSM3{3.0.0d} [More Swords 3](MSM-SNAP-3.0.0e-For-MC-1.7.10.jar) Unloaded->Constructed->Pre-initialized
    MultiPageChest{1.3.3} [Multi Page Chest](MultiPageChest-1.3.3-MC1.7.10.jar) Unloaded->Constructed->Pre-initialized
    NEIPlugins{1.1.0.10-unofficial} [NEI Plugins Unofficial](NEIPlugins-MC1.7.10-1.1.0.10-unofficial.jar) Unloaded->Constructed->Pre-initialized
    OpenMods{0.6} [OpenMods](OpenModsLib-1.7.10-0.6-snapshot-224.jar) Unloaded->Constructed->Pre-initialized
    OpenBlocks{1.3} [OpenBlocks](OpenBlocks-1.7.10-1.3-snapshot-434.jar) Unloaded->Constructed->Pre-initialized
    OresPlus{0.7.3.41B} [OresPlus](OresPlus-0.7.3.41B.jar) Unloaded->Constructed->Pre-initialized
    OWG{1.0.0} [Old World Gen](OWG-1.0.0.jar) Unloaded->Constructed->Pre-initialized
    clayspawn{1.7.2a} [Pam's Clay Spawn](Pam's Clay Spawn 1.7.2a.zip) Unloaded->Constructed->Pre-initialized
    desertcraft{1.7.2b} [Pam's DesertCraft](Pam's DesertCraft 1.7.10a.zip) Unloaded->Constructed->Pre-initialized
    getalltheseeds{1.7.2a} [Pam's Get all the Seeds!](Pam's Get all the Seeds 1.7.2a.zip) Unloaded->Constructed->Pre-initialized
    harvestcraft{1.7.10b} [Pam's HarvestCraft](Pam's HarvestCraft 1.7.10c.jar) Unloaded->Constructed->Pre-initialized
    randomplants{1.7.2a} [Pam's RandomPlants](Pam's Random Pants 1.7.2a.zip) Unloaded->Constructed->Pre-initialized
    simplerecipes{1.7.2a} [Pam's Simple Recipes](Pam's Simple Recipes 1.7.2a.zip) Unloaded->Constructed->Pre-initialized
    temperateplants{1.7.2b} [Pam's Temperate Plants](Pam's Temperate Plants 1.7.2b.zip) Unloaded->Constructed->Pre-initialized
    weeeflowers{1.7.2b} [Pam's Weee! Flowers](Pam's WeeeFlowers 1.7.2b.zip) Unloaded->Constructed->Pre-initialized
    parachutemod{1.7.10} [Parachute Mod](parachutemod-1.7.10-2.5.5.jar) Unloaded->Constructed->Pre-initialized
    ProjRed|Transmission{4.4.9.49} [ProjectRed-Transmission](ProjectRed-Integration-1.7.10-4.4.9.49.jar) Unloaded->Constructed->Pre-initialized
    ProjRed|Exploration{4.4.9.49} [ProjectRed-Exploration](ProjectRed-World-1.7.10-4.4.9.49.jar) Unloaded->Constructed->Pre-initialized
    ProjRed|Compatibility{4.4.9.49} [ProjectRed-Compatibility](ProjectRed-Compat-1.7.10-4.4.9.49.jar) Unloaded->Constructed->Pre-initialized
    ProjRed|Integration{4.4.9.49} [ProjectRed-Integration](ProjectRed-Integration-1.7.10-4.4.9.49.jar) Unloaded->Constructed->Pre-initialized
    ProjRed|Illumination{4.4.9.49} [ProjectRed-Illumination](ProjectRed-Lighting-1.7.10-4.4.9.49.jar) Unloaded->Constructed->Pre-initialized
    rafradek_wallpaint{1.5.4} [Wall Painter](rafradek_wallpaint-1.5.4.jar) Unloaded->Constructed->Pre-initialized
    rainbowcraft{1.2} [RainbowCraft](RainbowCraft 1.2.4.jar) Unloaded->Constructed->Pre-initialized
    RedstonePasteMod{1.6.2} [Redstone Paste](RedstonePasteMod-1.7.10-1.6.2.jar) Unloaded->Constructed->Pre-initialized
    RopesPlus{1.6.3} [Ropes+](RopePlus-1.7.10.jar) Unloaded->Constructed->Pre-initialized
    RotaryCraft{Gamma} [RotaryCraft](RotaryCraft 1.7.10 V2.jar) Unloaded->Constructed->Pre-initialized
    RWG{Alpha 1.1} [Realistic World Gen Alpha](RWG-alpha-1.1.jar) Unloaded->Constructed->Pre-initialized
    secretroomsmod{4.7.1} [The SecretRoomsMod](secretroomsmod-1.7.10-4.7.1.373.jar) Unloaded->Constructed->Pre-initialized
    shadowworld{1.3.2} [Shadow World](shadowworld-1.3.2.jar) Unloaded->Constructed->Pre-initialized
    shadowworld/DynamicLights{1.0.0} [DynamicLights in the Shadow World](shadowworld_DynamicLights_1.0.0.jar) Unloaded->Constructed->Pre-initialized
    staircraftmod{1.7} [Staircraft](Staircraftmod 1.7 - 1.7.10 Forge.jar) Unloaded->Constructed->Pre-initialized
    Tails{1.7.10-1.2.2} [Tails](Tails-1.7.10-1.2.2.jar) Unloaded->Constructed->Pre-initialized
    TallDoors{0.5.1} [Tall Doors Mod](TallDoors-1.7.10-0.5.2.jar) Unloaded->Constructed->Pre-initialized
    TF2Dispenser{1.7.10} [TF2 Dispenser](TF2Dispenser-1.7.10.jar) Unloaded->Constructed->Pre-initialized
    TF2Teleporter{1.7.10} [TF2 Teleporter](TF2Teleporter-1.7.10.jar) Unloaded->Constructed->Pre-initialized
    ThaumcraftMobAspects{1.7.2-2A} [Thaumcraft Mob Aspects](ThaumcraftMobAspects-1.7.2-2A.jar) Unloaded->Constructed->Pre-initialized
    axetomahawk.core{1.5.0.3-1.7.10} [Tomahawks Core](tomahawk-1.5.0.3-1.7.10.jar) Unloaded->Constructed->Pre-initialized
    axetomahawk{1.5.0.3-1.7.10} [Tomahawks](tomahawk-1.5.0.3-1.7.10.jar) Unloaded->Constructed->Pre-initialized
    Torched{4.0.0} [Torched](Torched-4.0.0.jar) Unloaded->Constructed->Pre-initialized
    TrailMix{4.0.0} [TrailMix](TrailMix-4.0.0.jar) Unloaded->Constructed->Pre-initialized
    TwilightForest{2.3.2} [The Twilight Forest](twilightforest-1.7.10-2.3.2.jar) Unloaded->Constructed->Pre-initialized
    AS_UpdateCheck{1.1.6} [AtomicStryker Update Check Mod](UpdateCheckerMod-1.7.10.jar) Unloaded->Constructed->Pre-initialized
    warpbook{2.0.34} [Warp Book](warpbook-2.0.34.jar) Unloaded->Constructed->Pre-initialized
    weaponmod{v1.14.3} [Balkon's WeaponMod](weaponmod-1.14.3.jar) Unloaded->Constructed->Pre-initialized
    witchery{0.20.6} [Witchery](witchery-1.7.10-0.20.6.jar) Unloaded->Constructed->Pre-initialized
    yarr_cutemobmodels{1.0.8} [Cute Mob Models](yarrcutemobmodels-1.0.8-1.7.10.jar) Unloaded->Constructed->Pre-initialized
    THKaguyaMod{2.82_1.7.10} [Itutu no Nandai MOD+](五つの難題MOD+ ver2.82-1.7.10.zip) Unloaded->Constructed->Pre-initialized
    McMultipart{1.1.0.300} [Minecraft Multipart Plugin](ForgeMultipart-1.7.10-1.1.0.300-universal.jar) Unloaded->Constructed->Pre-initialized
    ForgeMicroblock{1.1.0.300} [Forge Microblocks](ForgeMultipart-1.7.10-1.1.0.300-universal.jar) Unloaded->Constructed->Pre-initialized
    AE2 Version: stable rv0-stable-10 for Forge 10.13.0.1152
    Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: optifine [/spoiler]
